package rebue.onl.ro;

public class GetOnlinesRo {

	/**
	 * This field was generated by MyBatis Generator.
	 *
	 * 返回值 1:成功 -1:失败
	 *
	 * @mbg.generated
	 */
	private Byte result;

	/**
	 * 上线信息
	 */
	private OnlinesRo record;

	public Byte getResult() {
		return result;
	}

	public void setResult(Byte result) {
		this.result = result;
	}

	public OnlinesRo getRecord() {
		return record;
	}

	public void setRecord(OnlinesRo record) {
		this.record = record;
	}

	@Override
	public String toString() {
		return "GetOnlinesRo [result=" + result + ", record=" + record + "]";
	}

}
