package rebue.onl.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.onl.mo.OnlCartMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface OnlCartMapper extends MybatisBaseMapper<OnlCartMo, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_CART
     *
     * @mbg.generated 2018-03-26 15:41:46
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_CART
     *
     * @mbg.generated 2018-03-26 15:41:46
     */
    int insert(OnlCartMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_CART
     *
     * @mbg.generated 2018-03-26 15:41:46
     */
    int insertSelective(OnlCartMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_CART
     *
     * @mbg.generated 2018-03-26 15:41:46
     */
    OnlCartMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_CART
     *
     * @mbg.generated 2018-03-26 15:41:46
     */
    int updateByPrimaryKeySelective(OnlCartMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_CART
     *
     * @mbg.generated 2018-03-26 15:41:46
     */
    int updateByPrimaryKey(OnlCartMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_CART
     *
     * @mbg.generated 2018-03-26 15:41:46
     */
    List<OnlCartMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_CART
     *
     * @mbg.generated 2018-03-26 15:41:46
     */
    List<OnlCartMo> selectSelective(OnlCartMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_CART
     *
     * @mbg.generated 2018-03-26 15:41:46
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_CART
     *
     * @mbg.generated 2018-03-26 15:41:46
     */
    boolean existSelective(OnlCartMo record);
}