package rebue.onl.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.onl.mo.OnlOnlineSpecMo;
import rebue.robotech.mapper.MybatisBaseMapper;
import rebue.onl.ro.OnlOnlineSpecInfoRo;

@Mapper
public interface OnlOnlineSpecMapper
		extends
			MybatisBaseMapper<OnlOnlineSpecMo, Long> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ONL_ONLINE_SPEC
	 *
	 * @mbg.generated 2018-04-03 09:18:24
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ONL_ONLINE_SPEC
	 *
	 * @mbg.generated 2018-04-03 09:18:24
	 */
	int insert(OnlOnlineSpecMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ONL_ONLINE_SPEC
	 *
	 * @mbg.generated 2018-04-03 09:18:24
	 */
	int insertSelective(OnlOnlineSpecMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ONL_ONLINE_SPEC
	 *
	 * @mbg.generated 2018-04-03 09:18:24
	 */
	OnlOnlineSpecMo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ONL_ONLINE_SPEC
	 *
	 * @mbg.generated 2018-04-03 09:18:24
	 */
	int updateByPrimaryKeySelective(OnlOnlineSpecMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ONL_ONLINE_SPEC
	 *
	 * @mbg.generated 2018-04-03 09:18:24
	 */
	int updateByPrimaryKey(OnlOnlineSpecMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ONL_ONLINE_SPEC
	 *
	 * @mbg.generated 2018-04-03 09:18:24
	 */
	List<OnlOnlineSpecMo> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ONL_ONLINE_SPEC
	 *
	 * @mbg.generated 2018-04-03 09:18:24
	 */
	List<OnlOnlineSpecMo> selectSelective(OnlOnlineSpecMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ONL_ONLINE_SPEC
	 *
	 * @mbg.generated 2018-04-03 09:18:24
	 */
	boolean existByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ONL_ONLINE_SPEC
	 *
	 * @mbg.generated 2018-04-03 09:18:24
	 */
	boolean existSelective(OnlOnlineSpecMo record);

	/**
	 * 获取上线规格信息 Title: selectOnlineSpecInfoByOnlineId Description:
	 * 
	 * @param record
	 * @return
	 * @date 2018年4月1日 下午4:29:31
	 */
	List<OnlOnlineSpecInfoRo> selectOnlineSpecInfo(OnlOnlineSpecMo record);
}