package rebue.onl.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.onl.mo.OnlOnlineMo;
import rebue.robotech.mapper.MybatisBaseMapper;
import java.util.Map;
import rebue.onl.ro.OnlOnlineGoodsInfoRo;

@Mapper
public interface OnlOnlineMapper extends MybatisBaseMapper<OnlOnlineMo, Long> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ONL_ONLINE
	 *
	 * @mbg.generated 2018-04-08 11:13:11
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ONL_ONLINE
	 *
	 * @mbg.generated 2018-04-08 11:13:11
	 */
	int insert(OnlOnlineMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ONL_ONLINE
	 *
	 * @mbg.generated 2018-04-08 11:13:11
	 */
	int insertSelective(OnlOnlineMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ONL_ONLINE
	 *
	 * @mbg.generated 2018-04-08 11:13:11
	 */
	OnlOnlineMo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ONL_ONLINE
	 *
	 * @mbg.generated 2018-04-08 11:13:11
	 */
	int updateByPrimaryKeySelective(OnlOnlineMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ONL_ONLINE
	 *
	 * @mbg.generated 2018-04-08 11:13:11
	 */
	int updateByPrimaryKey(OnlOnlineMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ONL_ONLINE
	 *
	 * @mbg.generated 2018-04-08 11:13:11
	 */
	List<OnlOnlineMo> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ONL_ONLINE
	 *
	 * @mbg.generated 2018-04-08 11:13:11
	 */
	List<OnlOnlineMo> selectSelective(OnlOnlineMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ONL_ONLINE
	 *
	 * @mbg.generated 2018-04-08 11:13:11
	 */
	boolean existByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ONL_ONLINE
	 *
	 * @mbg.generated 2018-04-08 11:13:11
	 */
	boolean existSelective(OnlOnlineMo record);

	/**
	 * 获取上线商品列表 Title: selectOnlineGoodsList Description:
	 * 
	 * @return
	 * @date 2018年3月29日 下午5:39:41
	 */
	List<OnlOnlineGoodsInfoRo> selectOnlineGoodsList(Map<String, Object> map);
	
	/**
	 * 判断产品是否已上线
	 * Title: existOnlineByProduceId
	 * Description: 
	 * @param record
	 * @return
	 * @date 2018年4月12日 下午4:33:35
	 */
	boolean existOnlineByProduceId(OnlOnlineMo record);
}