package rebue.onl.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;

import rebue.onl.mo.OnlOnlineMo;
import rebue.onl.ro.OnlOnlineGoodsInfoRo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface OnlOnlineMapper extends MybatisBaseMapper<OnlOnlineMo, Long> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table ONL_ONLINE
	 *
	 * @mbg.generated 2018-03-26 15:41:46
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table ONL_ONLINE
	 *
	 * @mbg.generated 2018-03-26 15:41:46
	 */
	int insert(OnlOnlineMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table ONL_ONLINE
	 *
	 * @mbg.generated 2018-03-26 15:41:46
	 */
	int insertSelective(OnlOnlineMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table ONL_ONLINE
	 *
	 * @mbg.generated 2018-03-26 15:41:46
	 */
	OnlOnlineMo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table ONL_ONLINE
	 *
	 * @mbg.generated 2018-03-26 15:41:46
	 */
	int updateByPrimaryKeySelective(OnlOnlineMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table ONL_ONLINE
	 *
	 * @mbg.generated 2018-03-26 15:41:46
	 */
	int updateByPrimaryKey(OnlOnlineMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table ONL_ONLINE
	 *
	 * @mbg.generated 2018-03-26 15:41:46
	 */
	List<OnlOnlineMo> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table ONL_ONLINE
	 *
	 * @mbg.generated 2018-03-26 15:41:46
	 */
	List<OnlOnlineMo> selectSelective(OnlOnlineMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table ONL_ONLINE
	 *
	 * @mbg.generated 2018-03-26 15:41:46
	 */
	boolean existByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table ONL_ONLINE
	 *
	 * @mbg.generated 2018-03-26 15:41:46
	 */
	boolean existSelective(OnlOnlineMo record);
	
	/**
	 * 获取上线商品列表
	 * Title: selectOnlineGoodsList
	 * Description: 
	 * @return
	 * @date 2018年3月29日 下午5:39:41
	 */
	List<OnlOnlineGoodsInfoRo> selectOnlineGoodsList(Map<String, Object> map);
	
}