package rebue.onl.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.onl.mo.OnlOnlineLogMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface OnlOnlineLogMapper extends MybatisBaseMapper<OnlOnlineLogMo, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_LOG
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_LOG
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    int insert(OnlOnlineLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_LOG
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    int insertSelective(OnlOnlineLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_LOG
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    OnlOnlineLogMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_LOG
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    int updateByPrimaryKeySelective(OnlOnlineLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_LOG
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    int updateByPrimaryKey(OnlOnlineLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_LOG
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    List<OnlOnlineLogMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_LOG
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    List<OnlOnlineLogMo> selectSelective(OnlOnlineLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_LOG
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_LOG
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    boolean existSelective(OnlOnlineLogMo record);
}