package rebue.onl.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.onl.mo.OnlOnlinePicMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface OnlOnlinePicMapper extends MybatisBaseMapper<OnlOnlinePicMo, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_PIC
     *
     * @mbg.generated 2018-04-17 10:22:47
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_PIC
     *
     * @mbg.generated 2018-04-17 10:22:47
     */
    int insert(OnlOnlinePicMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_PIC
     *
     * @mbg.generated 2018-04-17 10:22:47
     */
    int insertSelective(OnlOnlinePicMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_PIC
     *
     * @mbg.generated 2018-04-17 10:22:47
     */
    OnlOnlinePicMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_PIC
     *
     * @mbg.generated 2018-04-17 10:22:47
     */
    int updateByPrimaryKeySelective(OnlOnlinePicMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_PIC
     *
     * @mbg.generated 2018-04-17 10:22:47
     */
    int updateByPrimaryKey(OnlOnlinePicMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_PIC
     *
     * @mbg.generated 2018-04-17 10:22:47
     */
    List<OnlOnlinePicMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_PIC
     *
     * @mbg.generated 2018-04-17 10:22:47
     */
    List<OnlOnlinePicMo> selectSelective(OnlOnlinePicMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_PIC
     *
     * @mbg.generated 2018-04-17 10:22:47
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_PIC
     *
     * @mbg.generated 2018-04-17 10:22:47
     */
    boolean existSelective(OnlOnlinePicMo record);
}