package rebue.onl.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.onl.mo.OnlOnlineSpecLogMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface OnlOnlineSpecLogMapper extends MybatisBaseMapper<OnlOnlineSpecLogMo, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_SPEC_LOG
     *
     * @mbg.generated 2018-04-02 18:36:49
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_SPEC_LOG
     *
     * @mbg.generated 2018-04-02 18:36:49
     */
    int insert(OnlOnlineSpecLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_SPEC_LOG
     *
     * @mbg.generated 2018-04-02 18:36:49
     */
    int insertSelective(OnlOnlineSpecLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_SPEC_LOG
     *
     * @mbg.generated 2018-04-02 18:36:49
     */
    OnlOnlineSpecLogMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_SPEC_LOG
     *
     * @mbg.generated 2018-04-02 18:36:49
     */
    int updateByPrimaryKeySelective(OnlOnlineSpecLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_SPEC_LOG
     *
     * @mbg.generated 2018-04-02 18:36:49
     */
    int updateByPrimaryKey(OnlOnlineSpecLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_SPEC_LOG
     *
     * @mbg.generated 2018-04-02 18:36:49
     */
    List<OnlOnlineSpecLogMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_SPEC_LOG
     *
     * @mbg.generated 2018-04-02 18:36:49
     */
    List<OnlOnlineSpecLogMo> selectSelective(OnlOnlineSpecLogMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_SPEC_LOG
     *
     * @mbg.generated 2018-04-02 18:36:49
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_SPEC_LOG
     *
     * @mbg.generated 2018-04-02 18:36:49
     */
    boolean existSelective(OnlOnlineSpecLogMo record);
}