package rebue.onl.mo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Database Table Remarks:
 *   上线日志
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ONL_ONLINE_LOG
 *
 * @mbg.generated do_not_delete_during_merge 2018-04-02 18:36:48
 */
@ApiModel(value = "OnlOnlineLogMo", description = "上线日志")
@JsonInclude(Include.NON_NULL)
public class OnlOnlineLogMo implements Serializable {
    /**
     * Database Column Remarks:
     *   上线日志ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONL_ONLINE_LOG.ID
     *
     * @mbg.generated 2018-04-02 18:36:48
     */
    @ApiModelProperty(value = "上线日志ID")
    private Long id;

    /**
     * Database Column Remarks:
     *   操作人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONL_ONLINE_LOG.OP_ID
     *
     * @mbg.generated 2018-04-02 18:36:48
     */
    @ApiModelProperty(value = "操作人ID")
    private Long opId;

    /**
     * Database Column Remarks:
     *   操作时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONL_ONLINE_LOG.OP_TIME
     *
     * @mbg.generated 2018-04-02 18:36:48
     */
    @ApiModelProperty(value = "操作时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date opTime;

    /**
     * Database Column Remarks:
     *   上线ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONL_ONLINE_LOG.ONLINE_ID
     *
     * @mbg.generated 2018-04-02 18:36:48
     */
    @ApiModelProperty(value = "上线ID")
    private Long onlineId;

    /**
     * Database Column Remarks:
     *   上线标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONL_ONLINE_LOG.ONLINE_TITLE
     *
     * @mbg.generated 2018-04-02 18:36:48
     */
    @ApiModelProperty(value = "上线标题")
    private String onlineTitle;

    /**
     * Database Column Remarks:
     *   上线描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONL_ONLINE_LOG.ONLINE_DETAIL
     *
     * @mbg.generated 2018-04-02 18:36:48
     */
    @ApiModelProperty(value = "上线描述")
    private String onlineDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ONL_ONLINE_LOG
     *
     * @mbg.generated 2018-04-02 18:36:48
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONL_ONLINE_LOG.ID
     *
     * @return the value of ONL_ONLINE_LOG.ID
     *
     * @mbg.generated 2018-04-02 18:36:48
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONL_ONLINE_LOG.ID
     *
     * @param id the value for ONL_ONLINE_LOG.ID
     *
     * @mbg.generated 2018-04-02 18:36:48
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONL_ONLINE_LOG.OP_ID
     *
     * @return the value of ONL_ONLINE_LOG.OP_ID
     *
     * @mbg.generated 2018-04-02 18:36:48
     */
    public Long getOpId() {
        return opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONL_ONLINE_LOG.OP_ID
     *
     * @param opId the value for ONL_ONLINE_LOG.OP_ID
     *
     * @mbg.generated 2018-04-02 18:36:48
     */
    public void setOpId(Long opId) {
        this.opId = opId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONL_ONLINE_LOG.OP_TIME
     *
     * @return the value of ONL_ONLINE_LOG.OP_TIME
     *
     * @mbg.generated 2018-04-02 18:36:48
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONL_ONLINE_LOG.OP_TIME
     *
     * @param opTime the value for ONL_ONLINE_LOG.OP_TIME
     *
     * @mbg.generated 2018-04-02 18:36:48
     */
    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONL_ONLINE_LOG.ONLINE_ID
     *
     * @return the value of ONL_ONLINE_LOG.ONLINE_ID
     *
     * @mbg.generated 2018-04-02 18:36:48
     */
    public Long getOnlineId() {
        return onlineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONL_ONLINE_LOG.ONLINE_ID
     *
     * @param onlineId the value for ONL_ONLINE_LOG.ONLINE_ID
     *
     * @mbg.generated 2018-04-02 18:36:48
     */
    public void setOnlineId(Long onlineId) {
        this.onlineId = onlineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONL_ONLINE_LOG.ONLINE_TITLE
     *
     * @return the value of ONL_ONLINE_LOG.ONLINE_TITLE
     *
     * @mbg.generated 2018-04-02 18:36:48
     */
    public String getOnlineTitle() {
        return onlineTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONL_ONLINE_LOG.ONLINE_TITLE
     *
     * @param onlineTitle the value for ONL_ONLINE_LOG.ONLINE_TITLE
     *
     * @mbg.generated 2018-04-02 18:36:48
     */
    public void setOnlineTitle(String onlineTitle) {
        this.onlineTitle = onlineTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONL_ONLINE_LOG.ONLINE_DETAIL
     *
     * @return the value of ONL_ONLINE_LOG.ONLINE_DETAIL
     *
     * @mbg.generated 2018-04-02 18:36:48
     */
    public String getOnlineDetail() {
        return onlineDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONL_ONLINE_LOG.ONLINE_DETAIL
     *
     * @param onlineDetail the value for ONL_ONLINE_LOG.ONLINE_DETAIL
     *
     * @mbg.generated 2018-04-02 18:36:48
     */
    public void setOnlineDetail(String onlineDetail) {
        this.onlineDetail = onlineDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_LOG
     *
     * @mbg.generated 2018-04-02 18:36:48
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", opId=").append(opId);
        sb.append(", opTime=").append(opTime);
        sb.append(", onlineId=").append(onlineId);
        sb.append(", onlineTitle=").append(onlineTitle);
        sb.append(", onlineDetail=").append(onlineDetail);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_LOG
     *
     * @mbg.generated 2018-04-02 18:36:48
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OnlOnlineLogMo other = (OnlOnlineLogMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_LOG
     *
     * @mbg.generated 2018-04-02 18:36:48
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}