package rebue.onl.mo;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Database Table Remarks:
 *   上线规格日志
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ONL_ONLINE_SPEC_LOG
 *
 * @mbg.generated do_not_delete_during_merge 2018-03-26 15:41:47
 */
@ApiModel(value = "OnlOnlineSpecLogMo", description = "上线规格日志")
@JsonInclude(Include.NON_NULL)
public class OnlOnlineSpecLogMo implements Serializable {
    /**
     * Database Column Remarks:
     *   上线规格日志ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONL_ONLINE_SPEC_LOG.ID
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    @ApiModelProperty(value = "上线规格日志ID")
    private Long id;

    /**
     * Database Column Remarks:
     *   上线日志ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONL_ONLINE_SPEC_LOG.ONLINE_LOG_ID
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    @ApiModelProperty(value = "上线日志ID")
    private Long onlineLogId;

    /**
     * Database Column Remarks:
     *   上线规格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONL_ONLINE_SPEC_LOG.ONLINE_SPEC
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    @ApiModelProperty(value = "上线规格")
    private String onlineSpec;

    /**
     * Database Column Remarks:
     *   销售价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONL_ONLINE_SPEC_LOG.SALE_PRICE
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    @ApiModelProperty(value = "销售价格")
    private BigDecimal salePrice;

    /**
     * Database Column Remarks:
     *   返现金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONL_ONLINE_SPEC_LOG.CASHBACK_AMOUNT
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    @ApiModelProperty(value = "返现金额")
    private BigDecimal cashbackAmount;

    /**
     * Database Column Remarks:
     *   销售数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONL_ONLINE_SPEC_LOG.SALE_COUNT
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    @ApiModelProperty(value = "销售数量")
    private Integer saleCount;

    /**
     * Database Column Remarks:
     *   排序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONL_ONLINE_SPEC_LOG.SEQ_NO
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    @ApiModelProperty(value = "排序号")
    private Integer seqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ONL_ONLINE_SPEC_LOG
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONL_ONLINE_SPEC_LOG.ID
     *
     * @return the value of ONL_ONLINE_SPEC_LOG.ID
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONL_ONLINE_SPEC_LOG.ID
     *
     * @param id the value for ONL_ONLINE_SPEC_LOG.ID
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONL_ONLINE_SPEC_LOG.ONLINE_LOG_ID
     *
     * @return the value of ONL_ONLINE_SPEC_LOG.ONLINE_LOG_ID
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    public Long getOnlineLogId() {
        return onlineLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONL_ONLINE_SPEC_LOG.ONLINE_LOG_ID
     *
     * @param onlineLogId the value for ONL_ONLINE_SPEC_LOG.ONLINE_LOG_ID
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    public void setOnlineLogId(Long onlineLogId) {
        this.onlineLogId = onlineLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONL_ONLINE_SPEC_LOG.ONLINE_SPEC
     *
     * @return the value of ONL_ONLINE_SPEC_LOG.ONLINE_SPEC
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    public String getOnlineSpec() {
        return onlineSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONL_ONLINE_SPEC_LOG.ONLINE_SPEC
     *
     * @param onlineSpec the value for ONL_ONLINE_SPEC_LOG.ONLINE_SPEC
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    public void setOnlineSpec(String onlineSpec) {
        this.onlineSpec = onlineSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONL_ONLINE_SPEC_LOG.SALE_PRICE
     *
     * @return the value of ONL_ONLINE_SPEC_LOG.SALE_PRICE
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    public BigDecimal getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONL_ONLINE_SPEC_LOG.SALE_PRICE
     *
     * @param salePrice the value for ONL_ONLINE_SPEC_LOG.SALE_PRICE
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    public void setSalePrice(BigDecimal salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONL_ONLINE_SPEC_LOG.CASHBACK_AMOUNT
     *
     * @return the value of ONL_ONLINE_SPEC_LOG.CASHBACK_AMOUNT
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    public BigDecimal getCashbackAmount() {
        return cashbackAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONL_ONLINE_SPEC_LOG.CASHBACK_AMOUNT
     *
     * @param cashbackAmount the value for ONL_ONLINE_SPEC_LOG.CASHBACK_AMOUNT
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    public void setCashbackAmount(BigDecimal cashbackAmount) {
        this.cashbackAmount = cashbackAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONL_ONLINE_SPEC_LOG.SALE_COUNT
     *
     * @return the value of ONL_ONLINE_SPEC_LOG.SALE_COUNT
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    public Integer getSaleCount() {
        return saleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONL_ONLINE_SPEC_LOG.SALE_COUNT
     *
     * @param saleCount the value for ONL_ONLINE_SPEC_LOG.SALE_COUNT
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    public void setSaleCount(Integer saleCount) {
        this.saleCount = saleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONL_ONLINE_SPEC_LOG.SEQ_NO
     *
     * @return the value of ONL_ONLINE_SPEC_LOG.SEQ_NO
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    public Integer getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONL_ONLINE_SPEC_LOG.SEQ_NO
     *
     * @param seqNo the value for ONL_ONLINE_SPEC_LOG.SEQ_NO
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    public void setSeqNo(Integer seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_SPEC_LOG
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", onlineLogId=").append(onlineLogId);
        sb.append(", onlineSpec=").append(onlineSpec);
        sb.append(", salePrice=").append(salePrice);
        sb.append(", cashbackAmount=").append(cashbackAmount);
        sb.append(", saleCount=").append(saleCount);
        sb.append(", seqNo=").append(seqNo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_SPEC_LOG
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OnlOnlineSpecLogMo other = (OnlOnlineSpecLogMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_SPEC_LOG
     *
     * @mbg.generated 2018-03-26 15:41:47
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}