package rebue.onl.mo;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 * Database Table Remarks:
 *   上线推广
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ONL_ONLINE_PROMOTION
 *
 * @mbg.generated do_not_delete_during_merge 2018-04-17 10:22:47
 */
@ApiModel(value = "OnlOnlinePromotionMo", description = "上线推广")
@JsonInclude(Include.NON_NULL)
public class OnlOnlinePromotionMo implements Serializable {
    /**
     * Database Column Remarks:
     *   上线推广ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONL_ONLINE_PROMOTION.ID
     *
     * @mbg.generated 2018-04-17 10:22:47
     */
    @ApiModelProperty(value = "上线推广ID")
    private Long id;

    /**
     * Database Column Remarks:
     *   上线ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONL_ONLINE_PROMOTION.ONLINE_ID
     *
     * @mbg.generated 2018-04-17 10:22:47
     */
    @ApiModelProperty(value = "上线ID")
    private Long onlineId;

    /**
     * Database Column Remarks:
     *   推广类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONL_ONLINE_PROMOTION.PROMOTION_TYPE
     *
     * @mbg.generated 2018-04-17 10:22:47
     */
    @ApiModelProperty(value = "推广类型")
    private Byte promotionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ONL_ONLINE_PROMOTION
     *
     * @mbg.generated 2018-04-17 10:22:47
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONL_ONLINE_PROMOTION.ID
     *
     * @return the value of ONL_ONLINE_PROMOTION.ID
     *
     * @mbg.generated 2018-04-17 10:22:47
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONL_ONLINE_PROMOTION.ID
     *
     * @param id the value for ONL_ONLINE_PROMOTION.ID
     *
     * @mbg.generated 2018-04-17 10:22:47
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONL_ONLINE_PROMOTION.ONLINE_ID
     *
     * @return the value of ONL_ONLINE_PROMOTION.ONLINE_ID
     *
     * @mbg.generated 2018-04-17 10:22:47
     */
    public Long getOnlineId() {
        return onlineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONL_ONLINE_PROMOTION.ONLINE_ID
     *
     * @param onlineId the value for ONL_ONLINE_PROMOTION.ONLINE_ID
     *
     * @mbg.generated 2018-04-17 10:22:47
     */
    public void setOnlineId(Long onlineId) {
        this.onlineId = onlineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONL_ONLINE_PROMOTION.PROMOTION_TYPE
     *
     * @return the value of ONL_ONLINE_PROMOTION.PROMOTION_TYPE
     *
     * @mbg.generated 2018-04-17 10:22:47
     */
    public Byte getPromotionType() {
        return promotionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONL_ONLINE_PROMOTION.PROMOTION_TYPE
     *
     * @param promotionType the value for ONL_ONLINE_PROMOTION.PROMOTION_TYPE
     *
     * @mbg.generated 2018-04-17 10:22:47
     */
    public void setPromotionType(Byte promotionType) {
        this.promotionType = promotionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_PROMOTION
     *
     * @mbg.generated 2018-04-17 10:22:47
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", onlineId=").append(onlineId);
        sb.append(", promotionType=").append(promotionType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_PROMOTION
     *
     * @mbg.generated 2018-04-17 10:22:47
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OnlOnlinePromotionMo other = (OnlOnlinePromotionMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONL_ONLINE_PROMOTION
     *
     * @mbg.generated 2018-04-17 10:22:47
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}